export const MENU_ITEM_LIST = [
  { id: 1, type: "block" },
  { id: 2, type: "text", src: "/images/mail.gif" },
  { id: 3, type: "block" },
  { id: 4, type: "block" },
  { id: 5, type: "text", src: "/images/cafe.gif" },
  { id: 6, type: "block" },
  { id: 7, type: "block" },
  { id: 8, type: "text", src: "/images/blog.gif" },
  { id: 9, type: "block" },
  { id: 10, type: "block" },
  { id: 11, type: "text", src: "/images/knowledge_in.gif" },
  { id: 12, type: "block" },
  { id: 13, type: "block" },
  { id: 14, type: "text", src: "/images/shopping.gif" },
  { id: 15, type: "block" },
  { id: 16, type: "block" },
  { id: 17, type: "text", src: "/images/pay.gif" },
  { id: 18, type: "block" },
  { id: 19, type: "block" },
  { id: 20, type: "text", src: "/images/TV.gif" },
  { id: 21, type: "block" },
  { id: 22, type: "block" },
  { id: 23, type: "text", src: "/images/dictionary.gif" },
  { id: 24, type: "block" },
  { id: 25, type: "block" },
  { id: 26, type: "text", src: "/images/news.gif" },
  { id: 27, type: "block" },
  { id: 28, type: "block" },
  { id: 29, type: "text", src: "/images/fund.gif" },
  { id: 30, type: "block" },
  { id: 31, type: "block" },
  { id: 32, type: "text", src: "/images/real_estate.gif" },
  { id: 33, type: "block" },
  { id: 34, type: "block" },
  { id: 35, type: "text", src: "/images/map.gif" },
  { id: 36, type: "block" },
  { id: 37, type: "block" },
  { id: 38, type: "text", src: "/images/movie.gif" },
  { id: 39, type: "block" },
  { id: 40, type: "block" },
  { id: 41, type: "text", src: "/images/music.gif" },
  { id: 42, type: "block" },
  { id: 43, type: "block" },
  { id: 44, type: "text", src: "/images/book.gif" },
  { id: 45, type: "block" },
  { id: 46, type: "block" },
  { id: 47, type: "text", src: "/images/webtoon.gif" },
  { id: 48, type: "block" },
  { id: 49, type: "block" },
  { id: 50, type: "text", src: "/images/bar.gif" },
  { id: 51, type: "block" },
  { id: 52, type: "text", src: "/images/more.gif" },
  { id: 53, type: "block" },
  { id: 54, type: "block" },
];
